---
# This .yml runs tests against the hyperconverged openebs setup
##########################################################################################
- hosts: localhost
  tasks:
    - slack: 
        token: "{{ lookup('env','SLACK_TOKEN') }}" 
        msg: "{{ ansible_date_time.time }} OPENEBS TESTSUITE: STARTED"
      when: slack_notify | bool and lookup('env','SLACK_TOKEN')
##########################################################################################
# TC NAME: pre-check
# TC DETAILS: Delete residue of playbooks before running the run-tests again
# TC NOTES:
#
- include: pre-check.yml
##########################################################################################
# TC NAME: 1) test-node-failure
# TC DETAILS: Test openebs behaviour when one of the nodes undergoes ungraceful shutdown
# TC NOTES:
#
- include: playbooks/resiliency/test-node-failure/test-node-failure.yml
##########################################################################################
# TC NAME: 2) test-kubelet-service-stop
# TC DETAILS: Test openebs behaviour when kubelet service is not running on one of the node
# TC NOTES:
#
#- include: playbooks/resiliency/test-kubelet-service-stop/test-kubelet-service-stop.yml
##########################################################################################
# TC NAME: 3) test-kubectl-snapshot
# TC DETAILS: Test to perform basic snapshot/clones using k8s api's
# TC NOTES:
#
#- include: playbooks/feature/snapshots/kubectl_snapshot/test-kubectl-snapshot.yml
###########################################################################################
# TC NAME: 4) test-k8s-memleak
# TC DETAILS: Test memory consumption on k8s cluster with openebs storage
# TC NOTES:
#
- include: playbooks/hyperconverged/test-k8s-memleak/memleak.yml
#
###########################################################################################
# TC NAME: 5) test-k8s-percona-mysql-pod
# TC DETAILS: Deploys percona pod on k8s cluster with openebs storage
# TC NOTES:           
#
- include: playbooks/hyperconverged/test-k8s-percona-mysql-pod/k8s-percona-pod.yml
#
###########################################################################################
# TC NAME: 6) test-k8s-jupyter-server-pod 
# TC DETAILS: Deploys jupyter notebook server on k8s cluster with openebs storage
# TC NOTES:           
#    
- include: playbooks/hyperconverged/test-k8s-jupyter-server-pod/k8s-jupyter-pod.yml
#
###########################################################################################
# TC NAME: 7) test-k8s-crunchy-postgres
# TC DETAILS: Deploys a postgresql cluster on k8s cluster with openebs storage
# TC NOTES:           
#    
- include: playbooks/hyperconverged/test-k8s-crunchy-postgres/k8s-crunchy-pg.yml
- include: pre-check.yml 
#
###########################################################################################
# TC NAME: 8) libiscsi-compliance-test-suite
# TC DETAILS: Runs the libiscsi iSCSI compliance suite on openebs storage
# TC NOTES:           
#    
- include: playbooks/compliance/iscsi/libiscsi.yml
#
###########################################################################################
# TC NAME: 9) snap-create-revert
# TC DETAILS: Creates a snapshot create and restore test on a simple openebs volume 
# TC NOTES:           
#    
- include: playbooks/feature/snapshots/simple-volume/snapshot.yml
#
###########################################################################################
# TC NAME: 10) mysql-snap-create-revert  
# TC DETAILS: Creates a mysql application snapshot on openebs volume and restore database 
# TC NOTES:           
#    
#- include: playbooks/feature/snapshots/percona-mysql/mysql-snapshot.yml
#
###########################################################################################
# TC NAME: 11) basic-ha-pod-reschedule  
# TC DETAILS: Tests basic ha upon openebs ctrl failures triggered by pod delete
# TC NOTES:           
#    
- include: playbooks/feature/ha/ha.yml 
###########################################################################################
# TC NAME: 12) deploy-application-in-own-ns
# TC DETAILS: Tests behaviour of openebs when application is running on its own ns
# TC NOTES:
#
- include: playbooks/hyperconverged/percona-openebs-ownnamespace/openebs-percona-diffns-pod.yml
###########################################################################################
# TC NAME: 13) volume_controller_pod_kill
# TC DETAILS: Tests resiliency upon random openebs ctrl failures caused by chaoskube
# TC NOTES:
#
- include: playbooks/resiliency/test-ctrl-failure/test-ctrl-failure.yml
- include: pre-check.yml
  when: is_vagrant_vm == true
##########################################################################################
# TC NAME: 14) volume_single_replica_pod_kill
# TC DETAILS: Tests resiliency upon random openebs replica failures (single) caused by chaoskube
# TC NOTES:
#
- include: playbooks/resiliency/test-single-replica-failure/test-single-replica-failure.yml
##########################################################################################
# TC NAME: 15) volume_replica_failure_with_quorum
# TC DETAILS: Tests resiliency upon random openebs replica failures (with quorum)
# TC NOTES:
#
- include: playbooks/resiliency/test-replica-quorum-failure/test-replica-quorum-failure.yml
##########################################################################################
# TC NAME: 16) volume_controller_lossy_network
# TC DETAILS: Tests resiliency upon lossy connectivity to openebs ctrl caused by pumba
# TC NOTES:
#
- include: playbooks/resiliency/test-network-failure/test-nw-failure.yml
##########################################################################################
# TC NAME: 17) volume_replica_lossy_network_with_quorum
# TC DETAILS: Tests resiliency upon lossy connectivity to openebs replica caused by pumba
# TC NOTES:
#
- include: playbooks/resiliency/test-network-failure-rep/test-nw-failure-rep.yml
##########################################################################################
# TC NAME: 18) node_loss_simulation_via_eviction_taint
# TC DETAILS: Simulates node loss by applying disk pressure taints to evict all pods
# TC NOTES:
- include: playbooks/resiliency/test-node-eviction-out-of-disk/test-node-eviction-out-of-disk.yml
##########################################################################################
# TC NAME: 19) cassandra load-gen test
# TC DETAILS: Tests cassandra deployment with load-generation
# TC NOTES:
- include: playbooks/hyperconverged/test-k8s-cassandra-pod/k8s-cassandra-pod.yml
##########################################################################################
# TC NAME: 20) test-k8s-drain-nodes
# TC DETAILS: Verify openebs behaviour when one of the node is drained.
# TC NOTES:
- include: playbooks/hyperconverged/test-k8s-drain-nodes/test-drain-nodes.yml
##########################################################################################
# TC NAME: 21) scaleup-cassandra-deployments
# TC DETAILS: Verify scaledup cassandra deployment has data sync.
# TC NOTES:
- include: playbooks/hyperconverged/test-scaleup-cassandra-pods/test-scaleup-cassandra-pods.yml
- include: pre-check.yml
  when: is_vagrant_vm == true
##########################################################################################
# TC NAME: 22) Application-upgrade-test
# TC DETAILS: Verify data availability post application rolling upgrade.
# TC NOTES:
- include: playbooks/hyperconverged/test-k8s-jenkins-upgrade/k8s-jenkins-upgrade.yml
##########################################################################################
# TC NAME: 23) pvc-svc-deletion-check
# TC DETAILS: Test to verify successful deletion of svc and pvc
# TC NOTES:
- include: playbooks/hyperconverged/test-k8s-pvc-deletion/k8s_delete_pvc.yml
##########################################################################################
# TC NAME: 24) scaleup-openebs-replicas
# TC DETAILS: Verify scaledup openebs replicas has data sync.
# TC NOTES:
- include: playbooks/hyperconverged/test-scaleup-storage-replicas/test-scaleup-storage-replicas.yml
##########################################################################################
# TC NAME: 25) Check replica affinity with node
# TC DETAILS: Verify the replica stickiness with the node.
# TC NOTES:
- include: playbooks/hyperconverged/test-replica-node-affinity/replica-node-affinity.yml
#########################################################################################
# TC NAME: 26) test-k8s-master-failure
# TC DETAILS: Test openebs behaviour when master nodes undergoes ungraceful shutdown
# TC NOTES:
#
- include: playbooks/resiliency/test-k8s-master-failure/k8s-master-failure.yml
########################################################################################## 
# TC NAME: 27) test-storage-pool
# TC DETAILS: Testing the storage pool path.
# TC NOTES:
#
- include: playbooks/hyperconverged/test-k8s-storage-pool/test-storage-pool.yml
##########################################################################################

# TC NAME: pre-check
# TC DETAILS: Delete residue of playbooks before running the run-tests again
# TC NOTES:
#
- include: pre-check.yml
##########################################################################################
- hosts: localhost
  roles:
    - {role: logging, when: logging | bool and deployment_mode == "hyperconverged"}
###########################################################################################

- hosts: localhost
  tasks:
    - slack: 
        token: "{{ lookup('env','SLACK_TOKEN') }}" 
        msg: "{{ ansible_date_time.time }} OPENEBS TESTSUITE: ENDED"
      when: slack_notify | bool and lookup('env','SLACK_TOKEN')
###########################################################################################
