apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{},"creationTimestamp":"2018-07-18T06:43:19Z","name":"openebs-percona","namespace":"","resourceVersion":"554421","selfLink":"/apis/storage.k8s.io/v1/storageclasses/openebs-percona","uid":"db64d9f6-8a55-11e8-bf54-42010a8a0fd7"},"parameters":{"openebs.io/capacity":"5G","openebs.io/jiva-replica-count":"2","openebs.io/storage-pool":"default","openebs.io/volume-monitor":"true"},"provisioner":"openebs.io/provisioner-iscsi","reclaimPolicy":"Delete"}
  creationTimestamp: 2018-07-18T07:02:04Z
  name: openebs-percona
  resourceVersion: "556172"
  selfLink: /apis/storage.k8s.io/v1/storageclasses/openebs-percona
  uid: 7a551731-8a58-11e8-bf54-42010a8a0fd7
parameters:
  openebs.io/capacity: 5G
  openebs.io/jiva-replica-count: "3"
  openebs.io/storage-pool: default
  openebs.io/volume-monitor: "true"
provisioner: openebs.io/provisioner-iscsi
reclaimPolicy: Delete
