---
openebs_operator_link: https://raw.githubusercontent.com/openebs/openebs/master/e2e/ansible/playbooks/hyperconverged/percona-openebs-ownnamespace/openebs-operator-ns-openebs.yaml

openebs_operator_alias: openebs-operator.yaml 

openebs_storageclasses_link: https://raw.githubusercontent.com/openebs/openebs/master/k8s/openebs-storageclasses.yaml

openebs_storageclasses_alias: openebs-storageclasses.yaml

# Image tag for openebs containers
# Accepted entries (ci, latest): Default: latest
test_tag: ci

namespace: openebs
