---
- name: Delete the iSCSI target
  shell: source ~/.profile; kubectl delete -f {{ volume_def }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm that the storage volume is deleted
  shell: source ~/.profile; kubectl get pvc
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'pvc' not in result.stdout"
  delay: 120
  retries: 6

- name: Confirm percona pod is deleted
  shell: >
    source ~/.profile;
    kubectl get pods -l name=percona --no-headers
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'percona' not in result.stdout"
  delay: 120
  retries: 6

