#kubectl-snapshot.yml
# Description: Test openebs snapshots using kubectl.

###############################################################################################
#Test Steps:

#1. Copy the test artifacts to k8s master.
#2. Check whether the OpenEBS components are deployed. Delete the Openebs components and create with ci tag.
#3. Deploy the snapshot controller.
#3. Deploy Percona application.
#4. Check if the application pod is up and running
#5. Check if the Percona service us up.
#6. Copy the mysql client files to the K8s node.
#7. Pull mysql client image and generate load.
#8. Calculate the checksum.
#9. Create snapshot.
#10. Restore the snapshot.
#11. Perform cleanup of test artifacts.
###############################################################################################

---
- hosts: localhost

  vars_files:
    - kubectl-snapshot-vars.yml

  tasks:
   - block:

       - name: Delete Openebs components
         shell: source ~/.profile; kubectl delete -f {{ openebs_link }}
         args: 
           executable: /bin/bash
         register: delete_openebs
         until: 
 
       - name: Get $HOME of K8s master for kubernetes user
         shell: source ~/.profile; echo $HOME
         args:
           executable: /bin/bash
         register: result_kube_home
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Deploy percona mysql pod
         shell: source ~/.profile; kubectl create -f {{ percona_link }}
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

       - name: Confirm pod status is running
         shell: source ~/.profile; kubectl get pods | grep percona
         args:
           executable: /bin/bash
         delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
         register: result
         until: "'percona' and 'Running' in result.stdout"
         delay: 120
         retries: 15


