---
- include_tasks: "{{utils_path}}/delete_deploy.yml"
  vars:
    app_yml: "{{volume_def }}"
    ns: "{{ namespace }}"

- name: Obtain the pvc name
  shell: source ~/.profile; kubectl get pvc -n {{ namespace }} --no-headers | awk '{print $1}'
  args:
    executable: /bin/bash
  register: pvc
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"


- name: Confirm that the storage volume is deleted
  shell: source ~/.profile; kubectl get pvc -n {{namespace}}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: " pvc.stdout not in result.stdout"
  delay: 30
  retries: 15
  changed_when: true

