---

test_name: test-k8s-master-failure


operator_ns: openebs

pod_yaml_alias:
  - jenkins.yml

namespace: k8s-master-failure

job_config_files:
  - template.xml
  - config_change.sh


test_pod_regex: maya*|openebs*|pvc*|jenkins*

test_log_path: setup/logs/master_failure_test.log

