---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basic-read
data:

 basic-rw : |-

     [global]
     directory=/datadir
     filesize=16m

     [basic-fio]
     rw=read
     bs=4k
     verify=crc32c
---
apiVersion: batch/v1
kind: Job
metadata:
  name: fio-read
spec:
  template:
    metadata:
      name: fio-read
    spec:
      restartPolicy: Never
      containers:
      - name: perfrunner
        image: openebs/tests-fio
        command: ["/bin/bash"]
        args: ["-c", "./fio_runner.sh --size 16m; exit 0"]
        volumeMounts:
           - mountPath: /datadir
             name: demo-snap-vol1
           - mountPath: templates/file/basic-rw
             subPath: basic-rw
             name: basic-configmap-read
        tty: true

      volumes:
      - name: demo-snap-vol1
        persistentVolumeClaim:
          claimName: demo-snap-vol-claim
      - name: basic-configmap-read
        configMap:
          name: basic-read
