       - name: Get the maya-apiser pod name
         shell: source ~/.profile; kubectl get pods -n openebs | grep maya-apiserver | awk '{print $1}'
         args:
           executable: /bin/bash
         register: mayapod
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         changed_when: True

       - name: Get the volume list
         shell: source ~/.profile; kubectl exec -it {{ mayapod.stdout }} -n openebs -- mayactl volume list
         args:
           executable: /bin/bash
         register: volname
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         changed_when: True

       - name: Get the volumes access mode
         shell: source ~/.profile; kubectl exec -it {{ mayapod.stdout }} -n openebs -- mayactl volume info --volname {{ volname.stdout.split()[2] }} -n {{ ns }}
         args:
           executable: /bin/bash
         register: result
         delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
         changed_when: True

       - name: Set RW count to a variable
         set_fact:
           vol_accessmode_count: "{{ result.stdout.count('RW') }}"

       - name: Verfy the replicas access mode
         command: echo "Verfiy the replicas access mode"
         when: vol_accessmode_count|int == (node_count)| int
         register: result
       - debug:
           msg: "All the PVCs are in sync"
         when: "result.rc == 0"

