---
- name: Copy the chaoskube specs to kubemaster
  copy:
    src: "{{ item }}"
    dest: "{{ result_kube_home.stdout }}"
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  with_items: "{{ files_to_copy }}"

