---
- name: Check pod status
  shell: source ~/.profile; kubectl get pods -n {{ ns }} -l {{ lkey }}={{ lvalue }}
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  until: "'Running' not in result.stdout"
  delay: 30
  retries: 15

