---
- name: Delete cStorPool
  shell: source ~/.profile; kubectl delete -f {{ result_kube_home.stdout }}/testspc.yaml
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Verify deployments are deleted
  shell: source ~/.profile; kubectl get deploy -n openebs 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: deploy_list
  until: "{{poolname}} not in deploy_list.stdout"

- name: Verify cStor Pool pods are deleted
  shell: source ~/.profile; kubectl get pods -n openebs 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: cstorpool_pods
  until: "{{poolname}} not in cstorpool_pods.stdout"
