---
- name: Delete deployed application files
  shell: source ~/.profile; kubectl delete -f {{ item }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items: "{{ app_yml }}"

