---
- name: Find regex in the log file
  shell: grep -i  {{item}} {{ path }}
  args:
    executable: /bin/bash
  delegate_to: "{{ destination_node }}"
  register: result
  ignore_errors: true
  with_items: 
    - "{{ string }}"
  
- name: Add observations to the log file
  lineinfile:
    dest: "{{ path }}"
    line: 'Observation'
  delegate_to: "{{ destination_node }}"

- name: Add observations to the log file
  blockinfile:
    dest: "{{ path }}"
    block:  "{{ item.stdout }}"
  delegate_to: "{{ destination_node }}"
  with_items: 
    - "{{ result.results }}"
