---
- name: Replace volume-claim name with test parameters
  replace:
    path: "{{ path }}"
    regexp: '{{ item.0 }}'
    replace: '{{ item.1 }}'
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  with_together:
    - "{{replace_item}}"
    - "{{replace_with}}"

