---
- name: Start the log aggregator to capture test pod logs
  shell: >
    source ~/.profile;
    nohup stern --all-namespaces "{{test_pod_regex}}"
    --kubeconfig {{result_kube_home.stdout}}/{{ kubeconfig }}
    --since 1m > {{result_kube_home.stdout}}/{{test_log_path}} &
  args:
    executable: /bin/bash
  become: true
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  when:  status == "start"

- name: Terminate the log aggregator
  shell: source ~/.profile; killall stern
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  become: true
  when:  status == "stop"
  ignore_errors: true
