---
- name: Update Testrail
  shell: source ~/.profile; python3 {{ inventory_dir | dirname }}/files/updater.py -tuser {{ testrail_user }} -tpass {{ testrail_password }} -sid {{ test_suite_id }} -cid {{ test_case_id }} -stid {{ status_id }}
  args:
    executable: /bin/bash
  register: result
  ignore_errors: yes

- name: Testrail Updated
  set_fact:
    tflag: "{{ result.stdout }}"