---
- name: Run apt-get update via shell
  command: apt-get update
  become: true
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  ignore_errors: true
  changed_when: true

- name: Install subversion on K8S-master
  command: apt-get install -y {{ item }}
  become: true
  with_items: "{{ deb_packages }}"
  delegate_to: "{{ groups['kubernetes-kubemasters'].0 }}"
  changed_when: true

- name: Get $HOME of K8s master for kubernetes user
  shell: source ~/.profile; echo $HOME
  args:
    executable: /bin/bash
  register: result_kube_home
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  changed_when: true

- include_tasks: "{{utils_path}}/stern_task.yml"
  vars:
    status: start
