---
- name: Getting the total number of disk in a nodes
  shell: gcloud compute disks list --filter="NAME:( {{ outer_item }} )" | grep disk | awk '{print $1}'
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: disk

- name: Detaching the disk from the nodes
  shell: >
    gcloud compute instances detach-disk {{ outer_item }} --disk {{ item }} --zone "{{ cluster_zone }}" &&
    gcloud compute disks delete --disk "{{ item }}" --zone "{{ cluster_zone }}"
  args:
    executable: /bin/bash
  register: result_disk
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  with_items:
     -  "{{ disk.stdout_lines }}"
