# The example Pod utilizing the profile loaded by the sample daemon.

apiVersion: v1
kind: Pod
metadata:
  name: cstor
  # Note that the Pod does not need to be in the same namespace as the loader.
  labels:
    app: cstor
spec:
#  serviceAccountName: openebs-maya-operator
  containers:
  - name: cstor-main-ctrl
    image: openebs/cstor-main:ci
    ports:
    - containerPort: 80
    securityContext: 
      privileged: true

    volumeMounts:
    - name: device
      mountPath: /host/dev     
      mountPropagation: Bidirectional
    - name: mount
      mountPath: /host/mnt
      mountPropagation: Bidirectional
    - name: etc
      mountPath: /host/etc
      mountPropagation: Bidirectional
    - name: tmp2
      mountPath: /tmp
      mountPropagation: Bidirectional

 
  - name:    cstor-repl-ctrl
    image: openebs/cstor-repl-ctrl:ci
    ports:
    - containerPort: 80
    securityContext: 
      privileged: true
    volumeMounts:
    - name: device
      mountPath: /host/dev
      mountPropagation: Bidirectional
    - name: mount
      mountPath: /host/mnt
      mountPropagation: Bidirectional
    - name: etc
      mountPath: /host/etc
      mountPropagation: Bidirectional
    - name: tmp2
      mountPath: /tmp
      mountPropagation: Bidirectional

  volumes:
  - name: device
    hostPath:
      # directory location on host
      path: /dev
      # this field is optional
      type: Directory
  - name: mount
    hostPath:
      path: /mnt
      type: Directory
  - name: etc
    hostPath:
      path: /etc
      type: Directory
  - name: tmp2
    hostPath:
      path: /tmp2
      type: Directory
