apiVersion: openebs.io/v1alpha1
kind: CStorPool
metadata:
  name: pool1-abc
  node: node-host-label
  labels:
    "kubernetes.io/hostname": "node-host-label"
  finalizers: ["openebs"]
spec:
  disks:
   diskList: ["/dev/sdb1"]
  poolSpec:
   cacheFile: /tmp/pool1.cache
   poolType: striped
   overProvisioning: false
status:
  phase: init
