apiVersion: openebs.io/v1alpha1
kind: CStorVolumeReplica
metadata:
  name: pvc-ee171da3-07d5-11e8-a5be-42010a8001be-cstor-rep-9440ab
  annotations:
    openebs.io/cstor-pool-guid: 7b99e406-1260-11e8-aa43-00505684eb2e

spec:
  cStorControllerIP: 10.210.102.206
  volName: vol1
  capacity: 1G
