apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagepoolclaims.openebs.io
spec:
  group: openebs.io
  names:
    kind: StoragePoolClaim
    listKind: StoragePoolClaimList
    plural: storagepoolclaims
    shortNames:
    - spc
  scope: Namespaced
  version: v1alpha1
