apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: storagepools.openebs.io
spec:
  group: openebs.io
  names:
    kind: StoragePool
    listKind: StoragePoolList
    plural: storagepools
    shortNames:
    - sp
  scope: Namespaced
  version: v1alpha1
