---
- name: Delete cassandra service pod 
  shell: source {{ profile }}; kubectl delete -f {{ svc_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Delete cassandra statefulset pod
  shell: source {{ profile }}; kubectl delete -f {{ stateful_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Delete cassandra loadgen pod
  shell: source {{ profile }}; kubectl delete -f {{ loadgen_yaml_alias }}
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Get pvcs
  shell: source {{ profile }}; kubectl get pvc -o custom-columns=:metadata.name --no-headers | grep cassandra-data
  args:
    executable: /bin/bash
  register: result
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Delete pvcs
  shell: source {{ profile }}; kubectl delete pvc {{ item }}
  args:
    executable: /bin/bash
  with_items:
    - "{{ result.stdout_lines }}"
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm cassandra pod has been deleted
  shell: source {{ profile }}; kubectl get pods
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  register: result
  until: "'cassandra' not in result.stdout"
  delay: 120 
  retries: 6

- name: Delete the openebs operator 
  shell: source ~/.profile; kubectl delete -f "{{ openebs_operator_link }}" 
  args:
    executable: /bin/bash
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Confirm pod has been deleted
  shell: source ~/.profile; kubectl get pods --all-namespaces
  args:
    executable: /bin/bash
  register: result
  until: "'maya-apiserver' or 'openebs-provisioner' not in result.stdout"
  delay: 100
  retries: 6
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"
  
- name: Remove cassandra svc file
  file:
    path: "{{ result_kube_home.stdout }}/{{ svc_yaml_alias }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Remove cassandra-stateful file
  file:
    path: "{{ result_kube_home.stdout }}/{{ stateful_yaml_alias }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"

- name: Remove cassandra loadgen file
  file:
    path: "{{ result_kube_home.stdout }}/{{ loadgen_yaml_alias }}"
    state: absent
  delegate_to: "{{groups['kubernetes-kubemasters'].0}}"



