---
test_name: test-disk-failure

utils_path: openebs/e2e/ansible/playbooks/utils

create_sc: storage-class.yaml

storage_pool_link: https://raw.githubusercontent.com/openebs/openebs/master/e2e/ansible/playbooks/hyperconverged/test-k8s-storage-pool/storage-pool-path_creation.yml

sql_test_link: https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/sql-test.sh

percona_link: https://raw.githubusercontent.com/openebs/elves/master/e2e/percona-liveness/percona.yaml

replace_item:
  - default
  - /mnt/openebs

replace_with:
  - disk
  - "{{result_mountpoint.stdout}}"
