# delete-cStorPool.yml
# Author: Sudarshan
# Description: Test playbook to de-provision cstor pool deployment.
###############################################################################################
#Test steps:
#1. Delete cstor pool deployment
#4. Verifies successful deletion of cstor pool pods and deployments
###############################################################################################
- hosts: localhost

  vars_files:
    - vars.yml

  tasks:
    - block:

        - include: pre-requisites.yml

        - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/delete_cStorPool.yml"
          when: storage_engine == 'cStor'

        - name: Test Passed
          set_fact:
            flag: "Test Passed"
            status_id: 1

        - name: Set Status
          set_fact:
            status: "good"

      rescue:
        - name: Test Failed
          set_fact:
            flag: "Test Failed"
            status_id: 5

        - name: Set Status
          set_fact:
            status: "danger"

      always:

        - include_tasks: "{{ansible_env.HOME}}/{{utils_path}}/stern_task.yml"
          vars:
            status: stop

        - name: Send slack notification
          slack:
            token: "{{ lookup('env','SLACK_TOKEN') }}"
            msg: '{{ ansible_date_time.time }} TEST: {{test_name}}, RESULT: {{ flag }},{{ cflag }}'
            color: "{{status}}"
          when: slack_notify | bool and lookup('env','SLACK_TOKEN')
